kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker

# kubeadmConfigPatches:
# - |
#   apiVersion: kubeadm.k8s.io/v1beta2
#   kind: InitConfiguration
#   metadata:
#     name: config
#   nodeRegistration:
#     kubeletExtraArgs:
#       "cloud-provider": "external"
